#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:10:00

#bl2bids

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Guiomar Niso

# make output directory
mkdir -p out_dir
mkdir -p out_figs

#python main.py
singularity exec docker://brainlife/mne:0.23dev python3 main.py

# Store PSD plot with alpha peak on product.json
cat << EOF > product.json
{
    "brainlife": [
       { 
           "type": "image/png", 
	       "name": "Epochs image",
           "base64": "$(base64 -w 0 out_figs/epochs_image.png)"
       },
       { 
           "type": "image/png", 
	       "name": "Epochs drop",
           "base64": "$(base64 -w 0 out_figs/epochs_drop.png)"
       },
       { 
           "type": "image/png", 
	       "name": "Epochs plot",
           "base64": "$(base64 -w 0 out_figs/epochs_plot.png)"
       },
       { 
           "type": "image/png", 
	       "name": "Epochs PSD",
           "base64": "$(base64 -w 0 out_figs/epochs_psd.png)"
       }
]
}
EOF



